# Generated by Django 6.0.1 on 2026-02-27 17:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('FREELANCE', 'freelance'), ('COMPANY', 'company'), ('ADMIN', 'admin')], default='FREELANCE', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_size', models.CharField(blank=True, choices=[('SMALL', '1-10 employés'), ('MEDIUM', '11-50 employés'), ('LARGE', '50-250 employés'), ('CORP', 'Plus de 250 employés')], max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_street', models.CharField(blank=True, max_length=200, null=True)),
                ('company_number', models.CharField(blank=True, max_length=10, null=True)),
                ('company_postcode', models.CharField(blank=True, max_length=200, null=True)),
                ('company_city', models.CharField(blank=True, max_length=200, null=True)),
                ('company_country', models.CharField(default='Belgique', max_length=200)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('company_description', models.TextField(blank=True, help_text="Présentation de l'entreprise et de sa culture")),
                ('company_website', models.URLField(blank=True, max_length=255, null=True)),
                ('company_TVA', models.CharField(blank=True, max_length=50, verbose_name='N° de TVA')),
                ('company_BCE', models.CharField(blank=True, max_length=50, verbose_name='N° BCE')),
                ('is_ready_for_validation', models.BooleanField(default=False, help_text='Coché automatiquement quand le profil est complet.')),
                ('company_is_active', models.BooleanField(default=False)),
                ('company_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
                ('company_sectors', models.ManyToManyField(blank=True, related_name='companies', to='users.sector')),
            ],
        ),
        migrations.CreateModel(
            name='FreeLanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelance_birth_date', models.DateField(blank=True, null=True)),
                ('freelance_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], max_length=1, null=True)),
                ('freelance_location', models.CharField(max_length=200)),
                ('freelance_full_remote', models.BooleanField(default=False)),
                ('freelance_enterprise_number', models.CharField(blank=True, help_text='N° de TVA ou Entreprise', max_length=50)),
                ('freelance_github_url', models.URLField(blank=True, max_length=255, null=True)),
                ('freelance_linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('freelance_website_url', models.URLField(blank=True, max_length=255, null=True)),
                ('freelance_availability', models.CharField(blank=True, choices=[('FULL', 'Temps plein'), ('PART', 'Temps partiel'), ('NONE', 'Indisponible')], max_length=4, null=True)),
                ('is_ready_for_validation', models.BooleanField(default=False, help_text='Coché automatiquement quand les 10 champs obligatoires sont remplis.')),
                ('freelance_is_active', models.BooleanField(default=False)),
                ('freelance_cv_file', models.FileField(blank=True, null=True, upload_to='cv_files/')),
                ('freelance_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_profile', to=settings.AUTH_USER_MODEL)),
                ('freelance_sectors', models.ManyToManyField(blank=True, related_name='freelances', to='users.sector')),
                ('freelance_soft_skills', models.ManyToManyField(blank=True, related_name='freelances', to='users.softskills')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('SEC', 'Secondaire'), ('BAC', 'Bachelier / Licence'), ('MAS', 'Master'), ('DOC', 'Doctorat'), ('PRO', 'Formation Pro / Certifiante')], default='BAC', max_length=3)),
                ('diploma_name', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=100)),
                ('year_obtained', models.PositiveIntegerField()),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='educ/')),
                ('is_verified', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.freelanceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=255)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='certs/')),
                ('is_verified', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.freelanceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('A1', 'Débutant'), ('A2', 'Élémentaire'), ('B1', 'Intermédiaire'), ('B2', 'Avancé'), ('C1', 'Autonome'), ('LM', 'Langue Maternelle')], max_length=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.freelanceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('AM', 'Cyclomoteur'), ('A', 'Moto'), ('B', 'Auto'), ('C', 'Poids Lourds'), ('D', 'Transport personnes'), ('BE', 'Remorque'), ('CACES_1', 'Nacelle R486 C1'), ('CACES_3', 'Chariot R489 C3'), ('ENGIN', 'Engin de chantier'), ('AUTRE', 'Autre')], max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='licenses/')),
                ('is_verified', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='users.freelanceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='HardSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.sector')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_location', models.CharField(max_length=200)),
                ('offer_title', models.CharField(max_length=200)),
                ('offer_description', models.TextField()),
                ('offer_created_at', models.DateTimeField(auto_now_add=True)),
                ('offer_is_active', models.BooleanField(default=True)),
                ('offer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='users.companyprofile')),
                ('offer_hardskills', models.ManyToManyField(blank=True, related_name='required_hardskills', to='users.hardskills')),
                ('offer_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sector')),
                ('offer_softskills', models.ManyToManyField(blank=True, related_name='required_softskills', to='users.softskills')),
            ],
        ),
        migrations.CreateModel(
            name='FreelanceSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='Niveau de 0 à 5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_levels', to='users.freelanceprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hardskills')),
            ],
            options={
                'unique_together': {('profile', 'skill')},
            },
        ),
    ]
