# Generated by Django 6.0.1 on 2026-01-27 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeLanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], max_length=1)),
                ('location', models.CharField(max_length=200)),
                ('full_remote', models.BooleanField(default=False)),
                ('enterprise_number', models.CharField(blank=True, help_text='N° de TVA ou Entreprise', max_length=50)),
                ('github_url', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('website_url', models.URLField(blank=True, max_length=255, null=True)),
                ('availability', models.CharField(choices=[('FULL', 'Temps plein'), ('PART', 'Temps partiel'), ('NONE', 'Indisponible')], max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv_files/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('SEC', 'Secondaire'), ('BAC', 'Bachelier / Licence'), ('MAS', 'Master'), ('DOC', 'Doctorat'), ('PRO', 'Formation Pro / Certifiante')], default='BAC', max_length=3)),
                ('diploma_name', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=100)),
                ('year_obtained', models.PositiveIntegerField()),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='educ/')),
                ('is_verified', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.freelanceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=255)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='certs/')),
                ('is_verified', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.freelanceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='HardSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(help_text='Niveau de 1 à 5')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hard_skills', to='users.freelanceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('A1', 'Débutant'), ('A2', 'Élémentaire'), ('B1', 'Intermédiaire'), ('B2', 'Avancé'), ('C1', 'Autonome'), ('LM', 'Langue Maternelle')], default='', max_length=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.freelanceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('AM', 'Cyclomoteur'), ('A', 'Moto'), ('B', 'Auto'), ('C', 'Poids Lourds'), ('D', 'Transport personnes'), ('BE', 'Remorque'), ('CACES_1', 'Nacelle R486 C1'), ('CACES_3', 'Chariot R489 C3'), ('ENGIN', 'Engin de chantier'), ('AUTRE', 'Autre')], max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='licenses/')),
                ('is_verified', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='users.freelanceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_skills', to='users.freelanceprofile')),
            ],
        ),
    ]
