# Generated by Django 6.0.1 on 2026-03-05 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('REVIEWING', "En cours d'examen"), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=20)),
                ('cover_message', models.TextField(blank=True, help_text="Message d'accompagnement optionnel", null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.freelanceprofile')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.joboffer')),
            ],
            options={
                'unique_together': {('job_offer', 'freelance')},
            },
        ),
    ]
