# Generated by Django 6.0.1 on 2026-02-05 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_companyprofile_freelanceprofile_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='availability',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='hardskills',
            name='level',
        ),
        migrations.RemoveField(
            model_name='hardskills',
            name='profile',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_BCE',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° BCE'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_TVA',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° de TVA'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_city',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_country',
            field=models.CharField(default='Belgique', max_length=200),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_description',
            field=models.TextField(blank=True, help_text="Présentation de l'entreprise et de sa culture"),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_postcode',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(choices=[('SMALL', '1-10 employés'), ('MEDIUM', '11-50 employés'), ('LARGE', '50-250 employés'), ('CORP', 'Plus de 250 employés')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_street',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('A1', 'Débutant'), ('A2', 'Élémentaire'), ('B1', 'Intermédiaire'), ('B2', 'Avancé'), ('C1', 'Autonome'), ('LM', 'Langue Maternelle')], max_length=2),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='companies', to='users.sector'),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='freelances', to='users.sector'),
        ),
        migrations.AddField(
            model_name='hardskills',
            name='sector',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.sector'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FreelanceSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(help_text='Niveau de 1 à 5')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_levels', to='users.freelanceprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hardskills')),
            ],
            options={
                'unique_together': {('profile', 'skill')},
            },
        ),
    ]
