# Generated by Django 6.0.1 on 2026-03-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceprofile',
            name='ai_cv_advice',
            field=models.TextField(blank=True, help_text='Dernier conseil IA généré pour le CV', null=True),
        ),
    ]
