# Generated by Django 6.0.1 on 2026-03-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_freelanceprofile_ai_cv_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
