# Generated by Django 6.0.1 on 2026-02-08 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sector_rename_availability_companyprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceskill',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, help_text='Niveau de 0 à 5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
