# Generated by Django 6.0.1 on 2026-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_freelanceprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rejection_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
