# Generated by Django 6.0.1 on 2026-02-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_freelanceskill_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='is_active',
            new_name='company_is_active',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='is_verified',
            new_name='company_is_verified',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='logo',
            new_name='company_logo',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='sectors',
            new_name='company_sectors',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='user',
            new_name='company_user',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='availability',
            new_name='freelance_availability',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='birth_date',
            new_name='freelance_birth_date',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='cv_file',
            new_name='freelance_cv_file',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='enterprise_number',
            new_name='freelance_enterprise_number',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='full_remote',
            new_name='freelance_full_remote',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='gender',
            new_name='freelance_gender',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='github_url',
            new_name='freelance_github_url',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='is_active',
            new_name='freelance_is_active',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='linkedin_url',
            new_name='freelance_linkedin_url',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='location',
            new_name='freelance_location',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='sectors',
            new_name='freelance_sectors',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='user',
            new_name='freelance_user',
        ),
        migrations.RenameField(
            model_name='freelanceprofile',
            old_name='website_url',
            new_name='freelance_website_url',
        ),
        migrations.RemoveField(
            model_name='softskills',
            name='profile',
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='freelance_soft_skills',
            field=models.ManyToManyField(blank=True, related_name='freelances', to='users.softskills'),
        ),
        migrations.AlterField(
            model_name='softskills',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_location', models.CharField(max_length=200)),
                ('offer_title', models.CharField(max_length=200)),
                ('offer_description', models.TextField()),
                ('offer_created_at', models.DateTimeField(auto_now_add=True)),
                ('offer_is_active', models.BooleanField(default=True)),
                ('offer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='users.companyprofile')),
                ('offer_hardskills', models.ManyToManyField(blank=True, related_name='required_hardskills', to='users.hardskills')),
                ('offer_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sector')),
                ('offer_softskills', models.ManyToManyField(blank=True, related_name='required_softskills', to='users.softskills')),
            ],
        ),
    ]
