# Generated by Django 6.0.1 on 2026-02-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_is_active_companyprofile_company_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_postcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('SMALL', '1-10 employés'), ('MEDIUM', '11-50 employés'), ('LARGE', '50-250 employés'), ('CORP', 'Plus de 250 employés')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceprofile',
            name='freelance_availability',
            field=models.CharField(blank=True, choices=[('FULL', 'Temps plein'), ('PART', 'Temps partiel'), ('NONE', 'Indisponible')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceprofile',
            name='freelance_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceprofile',
            name='freelance_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], max_length=1, null=True),
        ),
    ]
