# Generated by Django 6.0.1 on 2026-02-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_companyprofile_company_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceprofile',
            name='is_ready_for_validation',
            field=models.BooleanField(default=False, help_text='Coché automatiquement quand les 10 champs obligatoires sont remplis.'),
        ),
        migrations.AlterField(
            model_name='freelanceprofile',
            name='freelance_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
